# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name

    # Bus
    App\Common\Infrastructure\Bus\Symfony\Query\SymfonyQueryBus:
        class: App\Common\Infrastructure\Bus\Symfony\Query\SymfonyQueryBus
        arguments:
            $bus: '@query.bus'
    App\Common\Bus\Symfony\Query\QueryBus: '@App\Common\Infrastructure\Bus\Symfony\Query\SymfonyQueryBus'

    App\Common\Infrastructure\Bus\Symfony\Command\SymfonyCommandBus:
        class: App\Common\Infrastructure\Bus\Symfony\Command\SymfonyCommandBus
        arguments:
            $bus: '@command.bus'
    App\Common\Bus\Symfony\Command\CommandBus: '@App\Common\Infrastructure\Bus\Symfony\Command\SymfonyCommandBus'

    App\Common\Infrastructure\Bus\Symfony\Command\Middleware\PublishDomainEventsAfterCurrentBusMiddleware:
        class: App\Common\Infrastructure\Bus\Symfony\Command\Middleware\PublishDomainEventsAfterCurrentBusMiddleware
        arguments:
            $eventStore: '@App\Common\Domain\Event\EventStore'

    # Repository
    App\IdentityAccess\Infrastructure\Domain\Persistence\Doctrine\DoctrineUserRepository:
        class: App\IdentityAccess\Infrastructure\Domain\Persistence\Doctrine\DoctrineUserRepository
        arguments:
            $entityClass: 'App\IdentityAccess\Domain\User'
    App\IdentityAccess\Domain\UserRepository: '@App\IdentityAccess\Infrastructure\Domain\Persistence\Doctrine\DoctrineUserRepository'

    App\IdentityAccess\Infrastructure\Domain\Persistence\Doctrine\DoctrineRoleRepository:
        class: App\IdentityAccess\Infrastructure\Domain\Persistence\Doctrine\DoctrineRoleRepository
        arguments:
            $entityClass: 'App\IdentityAccess\Domain\Role'
    App\IdentityAccess\Domain\RoleRepository: '@App\IdentityAccess\Infrastructure\Domain\Persistence\Doctrine\DoctrineRoleRepository'

    App\IdentityAccess\Infrastructure\Domain\Persistence\Doctrine\EventStore\DoctrineEventStore:
        class: App\IdentityAccess\Infrastructure\Domain\Persistence\Doctrine\EventStore\DoctrineEventStore
        arguments:
            $registry: '@doctrine'
            $entityClass: 'App\Common\Domain\Event\StoredDomainEvent'
    App\Common\Domain\Event\EventStore: '@App\IdentityAccess\Infrastructure\Domain\Persistence\Doctrine\EventStore\DoctrineEventStore'

    # Domain service
    App\IdentityAccess\Infrastructure\Domain\Service\BcryptHasher:
        class: App\IdentityAccess\Infrastructure\Domain\Service\BcryptHasher
    App\IdentityAccess\Domain\Hasher: '@App\IdentityAccess\Infrastructure\Domain\Service\BcryptHasher'

    # Application
    App\IdentityAccess\Application\Command\RegisterUserHandler:
        class: App\IdentityAccess\Application\Command\RegisterUserHandler
        arguments:
            $userRepository: '@App\IdentityAccess\Domain\UserRepository'
            $passwordHasher: '@App\IdentityAccess\Domain\Hasher'

    App\IdentityAccess\Application\Command\CreateRoleHandler:
        class: App\IdentityAccess\Application\Command\CreateRoleHandler
        arguments:
            $roleRepository: '@App\IdentityAccess\Domain\RoleRepository'

    App\IdentityAccess\Application\Command\AssignRoleToUserHandler:
        class: App\IdentityAccess\Application\Command\AssignRoleToUserHandler
        arguments:
            $userRepository: '@App\IdentityAccess\Domain\UserRepository'
            $roleRepository: '@App\IdentityAccess\Domain\RoleRepository'

    # Symfony Command
    App\IdentityAccess\Infrastructure\Ui\Command\RegisterUserCommand:
        class: App\IdentityAccess\Infrastructure\Ui\Command\RegisterUserCommand
        arguments:
            $commandBus: '@App\Common\Infrastructure\Bus\Symfony\Command\SymfonyCommandBus'
        tags: [ 'console.command' ]

    App\IdentityAccess\Infrastructure\Ui\Command\CreateRoleCommand:
        class: App\IdentityAccess\Infrastructure\Ui\Command\CreateRoleCommand
        arguments:
            $commandBus: '@App\Common\Infrastructure\Bus\Symfony\Command\SymfonyCommandBus'
        tags: [ 'console.command' ]

    App\IdentityAccess\Infrastructure\Ui\Command\AssignRoleToUserCommand:
        class: App\IdentityAccess\Infrastructure\Ui\Command\AssignRoleToUserCommand
        arguments:
            $commandBus: '@App\Common\Infrastructure\Bus\Symfony\Command\SymfonyCommandBus'
        tags: [ 'console.command' ]