FROM aleksajo/nginx-unit-php:latest

COPY composer.json composer.lock /var/www/html/

CMD bash -c "update-ca-certificates && composer install --no-interaction && service supervisor start && unitd --no-daemon --control unix:/var/run/control.unit.sock"