doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
        types:
            uuid: App\Common\Infrastructure\Domain\Persistence\Doctrine\Type\Id
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            IdentityAccess:
                type: xml
                dir: '%kernel.project_dir%/src/IdentityAccess/Infrastructure/Domain/Persistence/Doctrine/Mapping'
                is_bundle: false
                prefix: App\IdentityAccess\Domain
            EventStore:
                type: xml
                dir: '%kernel.project_dir%/src/IdentityAccess/Infrastructure/Domain/Persistence/Doctrine/EventStore/Mapping'
                is_bundle: false
                prefix: App\Common\Domain\Event